chat:
  minimumSecondsBetweenBotMessages: 10
  minimumSecondsBetweenBotRepliesToSameUser: 20
  minimumSecondsBetweenModerationNotices: 5
  minimumSecondsBetweenModerationNoticesPerUser: 15

moderation:
  minimumSecondsBetweenModerationActionsPerUser: 300
  minimumSecondsBetweenEquivalentActions: 30

ai:
  minimumSecondsBetweenAiModerationReviewsForSameUser: 10
  minimumSecondsBetweenAiSocialReviewsForSameUser: 5
