chat:
  minimumSecondsBetweenBotMessages: 10
  minimumSecondsBetweenBotRepliesToSameUser: 20

moderation:
  minimumSecondsBetweenModerationActionsPerUser: 300
  minimumSecondsBetweenEquivalentActions: 30

ai:
  minimumSecondsBetweenAiReviewsForSameUser: 10
